#define __mscbl_cfg_text R"(

AppData: "~/Miscible"
AtlasDir: "$/atlas"
DBPath: "$/miscible.sqlite"

Settings:
  LogAge: 10                # delete logs older than this date
  ScanDepth: 15
  FontSize: 16.0

ViewSettings:
  SortBasis: 4
  Descending: 0

Models:
  BaseDir: "$/models"
  CLIPModel:
    Filename: "CLIP-ViT-B-32-laion2B-s34B-b79K.gguf"
    ModelHash: "badc55f957815de3bfe16ade2c381f6c21d32478c3ed3242dc2330f016e7d5b52ce6b1543e9da597a0a506da40ee544b32b84c776a2e7f749ba8e84ed7a316ba"
    ManifestHash: "e2dbd05f92dc087076ef59d78af6c10087ab145e3e8e4e355c43b896e5cd3620735b0e58670a8298aa8a7f6721457e19a265fee68a3e5b88ff5352b5f1279c09"
    ModelURL:
      - "https://github.com/mdhvg/miscible/releases/download/Model-CLIP-1.0/CLIP-ViT-B-32-laion2B-s34B-b79K.gguf"
    ManifestURL:
      - "https://github.com/mdhvg/miscible/releases/download/Model-CLIP-1.0/CLIP-ViT-B-32-laion2B-s34B-b79K.gguf.yaml"

#)"
